// benchmark-set/Console Tests/Vue.JS-Std.vue
<!-- @format -->

<template>
  <div>
    <div v-for="i in 100" :key="i">
      <span v-if="i % 5 === 0 && i % 7 === 0">Five-Seven</span>
      <span v-else-if="i % 5 === 0">Five</span>
      <span v-else-if="i % 7 === 0">Seven</span>
      <span v-else>{{ i }}</span>
    </div>
  </div>
</template>

<script>
  export default {
    name: "PrintNumbers",
  };
</script>

// Console Tests/React.JS-Std.jsx
/** @format */

import React from "react";

const PrintNumbers = () => {
  const renderNumbers = () => {
    let numbers = [];
    for (let i = 1; i <= 100; i++) {
      if (i % 5 === 0 && i % 7 === 0) {
        numbers.push(<div key={i}>Five-Seven</div>);
      } else if (i % 5 === 0) {
        numbers.push(<div key={i}>Five</div>);
      } else if (i % 7 === 0) {
        numbers.push(<div key={i}>Seven</div>);
      } else {
        numbers.push(<div key={i}>{i}</div>);
      }
    }
    return numbers;
  };

  return <div>{renderNumbers()}</div>;
};

export default PrintNumbers;
